### ISSUE TITLE
state on this?

### ISSUE THREAD

**Issue by WebFreak001** [jacob-carlborg/ddc#2]
It's hard to tell if this fork is ahead or behind of dmd because it's not registered as GitHub fork, but there hasn't been any activity in a while. What's the current state of this library?

**Comment by jacob-carlborg** [comment]
It's not currently up to date. So far it contains only very few changes compared to DMD. It's probably possible to just merge with DMD without getting any conflicts.

BTW, I enabled the GitHub Discussions features for this repository: https://github.com/jacob-carlborg/ddc/discussions.
